export const reportData = {
  meta: {
    title: "Informe mensual de supervision y valorizacion",
    reportNumber: "Informe mensual N. 01",
    period: "Del 01 al 30 de abril de 2026",
    issueDate: "11 de mayo de 2026",
    modality: "Administracion directa",
    standardFocus: "Directiva 017-2023-CG",
    sourceFile: "INFORME_SUPERVISOR_ABRIL_5fe5.pdf",
  },
  entity: {
    name: "Municipalidad Distrital de Union Ashaninka",
    area: "Gerencia de Desarrollo Territorial e Infraestructura",
    unit: "Unidad Funcional de Supervision y Liquidacion de Obras",
    governmentLevel: "Gobierno local",
    sector: "Educacion",
    functionalDivision: "047 Educacion Basica",
    functionalGroup: "0106 Educacion Secundaria",
    meta: "0129",
  },
  project: {
    name: "Construccion de aula de educacion secundaria, ambiente de usos multiples y servicios higienicos y/o vestidores para estudiantes; en el(la) I.E. 501390 distrito de Union Ashaninka, provincia La Convencion, departamento Cusco",
    cui: "2713723",
    snip: "N/C",
    infobras: "N/C",
    location: {
      department: "Cusco",
      province: "La Convencion",
      district: "Union Ashaninka",
      locality: "Santoshari",
      interventionZone: "I.E. 501390 - Santoshari",
      access: "Pichari - Santoshari, transporte todos, 36 km, 50 minutos. El acceso de vehiculos mayores llega a 3 metros de la obra; se recomienda acceso con vehiculos pequenos.",
    },
    description: "El IOARR contempla la instalacion de 02 aulas prefabricadas, servicios higienicos para estudiantes y docentes, y deposito, para atender la brecha de infraestructura educativa de la comunidad de Santoshari y comunidades aledanas.",
    physicalTargets: [
      "02 aulas prefabricadas de aproximadamente 65.52 m2 cada una",
      "Servicios higienicos para ninos, ninas y docentes",
      "Deposito de modulo prefabricado",
      "Equipamiento y mobiliario escolar",
      "Instalaciones sanitarias, electricas y mecanicas",
      "Plan de manejo ambiental y capacitacion",
    ],
    fundingSource: "Canon y sobrecanon, regalias, renta de aduanas y participaciones",
    approvalDocument: "Resolucion Gerencial N. 066-2026-MDUA/GM",
    approvalDate: "13 de febrero de 2026",
  },
  schedule: {
    startDate: "01 de abril de 2026",
    plannedEndDate: "29 de junio de 2026",
    approvedTermDays: 90,
    workStartAct: "01 de abril de 2026",
    stoppages: "N/C",
    extensions: "N/C",
    reprogrammedEndDate: "N/C",
    status: "Leve retraso",
    months: [
      {
        month: "Inicio 2026",
        programmedAmount: 0,
        programmedPercent: 0,
        programmedAccumulatedPercent: 0,
        executedPhysicalAmount: 0,
        executedPhysicalPercent: 0,
        executedPhysicalAccumulatedPercent: 0,
        executedFinancialAmount: 0,
        executedFinancialPercent: 0,
        executedFinancialAccumulatedPercent: 0,
      },
      {
        month: "Abril (01 al 30)",
        programmedAmount: 30421.09,
        programmedPercent: 7.21,
        programmedAccumulatedPercent: 7.21,
        executedPhysicalAmount: 25158.52,
        executedPhysicalPercent: 5.96,
        executedPhysicalAccumulatedPercent: 5.96,
        executedFinancialAmount: 58320,
        executedFinancialPercent: 9.87,
        executedFinancialAccumulatedPercent: 9.87,
      },
      {
        month: "Mayo (01 al 31)",
        programmedAmount: 64424.51,
        programmedPercent: 15.27,
        programmedAccumulatedPercent: 22.48,
        executedPhysicalAmount: 0,
        executedPhysicalPercent: 0,
        executedPhysicalAccumulatedPercent: 5.96,
        executedFinancialAmount: 0,
        executedFinancialPercent: 0,
        executedFinancialAccumulatedPercent: 9.87,
      },
      {
        month: "Junio (01 al 29)",
        programmedAmount: 327017.64,
        programmedPercent: 77.52,
        programmedAccumulatedPercent: 100,
        executedPhysicalAmount: 0,
        executedPhysicalPercent: 0,
        executedPhysicalAccumulatedPercent: 5.96,
        executedFinancialAmount: 0,
        executedFinancialPercent: 0,
        executedFinancialAccumulatedPercent: 9.87,
      },
    ],
  },
  financial: {
    initialInvestmentCost: 608248.24,
    approvedTechnicalFileBudget: 608248.24,
    baseWorkBudget: 565748.24,
    totalModifiedBudget: 608248.24,
    pim2026: 590798,
    pim2025: 17450,
    amountAssignedPim2026: 590798,
    amountDevenged: 58320,
    budgetBalance: 549928.24,
    balanceToAssign: 0.24,
    directCost: 421863.24,
    indirectCost: 143885,
    generalExpenses: 109260.67,
    supervisionExpenses: 34624.33,
    liquidationExpenses: 7500,
    technicalFileExpenses: 35000,
    currentPhysicalAmount: 25158.52,
    directCostBalance: 396704.72,
    currentWorkBudgetValuation: 33739.34,
    accumulatedWorkBudgetValuation: 33739.34,
  },
  progress: {
    programmed: {
      currentAmount: 30421.09,
      currentPercent: 7.21,
      accumulatedAmount: 30421.09,
      accumulatedPercent: 7.21,
    },
    executed: {
      currentAmount: 25158.52,
      currentPercent: 5.96,
      accumulatedAmount: 25158.52,
      accumulatedPercent: 5.96,
    },
    financial: {
      currentAmount: 58320,
      currentPercent: 9.87,
      accumulatedAmount: 58320,
      accumulatedPercent: 9.87,
    },
    gapPercent: -1.25,
    condition: "Leve retraso",
    note: "El avance financiero esta en funcion del PIM 2026 asignado.",
  },
  budgetBreakdown: [
    { concept: "Costo directo", approved: 421863.24, modified: 421863.24, percent: 69.36 },
    { concept: "Gastos generales", approved: 109260.67, modified: 109260.67, percent: 17.96 },
    { concept: "Gastos de supervision de obra", approved: 34624.33, modified: 34624.33, percent: 5.69 },
    { concept: "Gastos de liquidacion de obra", approved: 7500, modified: 7500, percent: 1.23 },
    { concept: "Gastos de elaboracion de expediente tecnico", approved: 35000, modified: 35000, percent: 5.75 },
    { concept: "Gastos de seguimiento", approved: 0, modified: 0, percent: 0 },
    { concept: "Gastos de evaluacion de expediente tecnico", approved: 0, modified: 0, percent: 0 },
    { concept: "Gastos de control concurrente", approved: 0, modified: 0, percent: 0 },
  ],
  analyticalBudget: [
    { code: "2.6.2 2.2.3", description: "Costo de construccion por administracion directa - personal", pim2026: 78461.83, executedToApril: 1888.97, balance2026: 76572.86 },
    { code: "2.6.2 2.2.4", description: "Costo de construccion por administracion directa - bienes", pim2026: 51925.29, executedToApril: 28584, balance2026: 23341.29 },
    { code: "2.6.2 2.2.5", description: "Costo de construccion por administracion directa - servicios", pim2026: 367266.79, executedToApril: 1340, balance2026: 365926.79 },
    { code: "2.6.3 2.2.2", description: "Mobiliario", pim2026: 31520, executedToApril: 2020, balance2026: 29500 },
    { code: "2.6.3 2.3.1", description: "Equipos computacionales y perifericos", pim2026: 1950, executedToApril: 1950, balance2026: 0 },
    { code: "2.6.8 1.3.1", description: "Elaboracion de expedientes tecnicos", pim2026: 35000, executedToApril: 34900, balance2026: 100 },
    { code: "2.6.8 1.4.1", description: "Gasto por la contratacion de personal", pim2026: 33153.33, executedToApril: 5087.03, balance2026: 28066.3 },
    { code: "2.6.8 1.4.2", description: "Gasto por la compra de bienes", pim2026: 871, executedToApril: 0, balance2026: 871 },
    { code: "2.6.8 1.4.3", description: "Gasto por la contratacion de servicios", pim2026: 8100, executedToApril: 0, balance2026: 8100 },
  ],
  components: [
    { item: "1.1", name: "Obras provisionales, trabajos preliminares, seguridad y salud", budget: 19824.7, current: 8670.47, accumulated: 8670.47, balance: 11154.23, progress: 43.74, nextMonthProgrammed: 11154.23 },
    { item: "1.2", name: "Estructuras", budget: 107202.29, current: 16488.05, accumulated: 16488.05, balance: 90714.24, progress: 15.38, nextMonthProgrammed: 90714.24 },
    { item: "1.3", name: "Arquitectura", budget: 236390.5, current: 0, accumulated: 0, balance: 236390.5, progress: 0, nextMonthProgrammed: 236390.5 },
    { item: "1.4", name: "Instalaciones sanitarias", budget: 17046.07, current: 0, accumulated: 0, balance: 17046.07, progress: 0, nextMonthProgrammed: 17046.07 },
    { item: "1.5", name: "Instalaciones electricas y mecanicas", budget: 33399.68, current: 0, accumulated: 0, balance: 33399.68, progress: 0, nextMonthProgrammed: 33399.68 },
    { item: "1.6", name: "Plan de manejo ambiental", budget: 4000, current: 0, accumulated: 0, balance: 4000, progress: 0, nextMonthProgrammed: 4000 },
    { item: "1.7", name: "Capacitacion", budget: 4000, current: 0, accumulated: 0, balance: 4000, progress: 0, nextMonthProgrammed: 4000 },
  ],
  executedItems: [
    { code: "01.01.01.01", description: "Almacen, oficinas y guardiania provisional (alquiler)", unit: "mes", metrado: 1, valuation: 1200, progress: 33.33 },
    { code: "01.01.01.02", description: "Cerco provisional de obra", unit: "m", metrado: 100, valuation: 2112, progress: 100 },
    { code: "01.01.01.03", description: "Cartel de identificacion de la obra de 4.80 x 3.60 m", unit: "und", metrado: 1, valuation: 1400, progress: 100 },
    { code: "01.01.03.01", description: "Trazo, niveles y replanteo durante el proceso", unit: "mes", metrado: 1, valuation: 538.47, progress: 33.33 },
    { code: "01.01.04.01", description: "Equipo de proteccion individual", unit: "glb", metrado: 1, valuation: 2700, progress: 100 },
    { code: "01.01.04.02", description: "Equipo de proteccion colectiva", unit: "glb", metrado: 1, valuation: 220, progress: 100 },
    { code: "01.01.04.03", description: "Senalizacion temporal de seguridad", unit: "glb", metrado: 1, valuation: 200, progress: 100 },
    { code: "01.01.04.04", description: "Recursos para respuestas ante emergencias en seguridad y salud durante el trabajo", unit: "glb", metrado: 1, valuation: 300, progress: 100 },
    { code: "01.02.01.01.01", description: "Corte de la plataforma", unit: "m3", metrado: 46.87, valuation: 659.46, progress: 100 },
    { code: "01.02.01.01.02", description: "Excavacion con maquinaria para cimiento corrido", unit: "m3", metrado: 26.69, valuation: 428.11, progress: 100 },
    { code: "01.02.01.01.03", description: "Excavacion manual de zanja para dado", unit: "m3", metrado: 3.46, valuation: 232.17, progress: 100 },
    { code: "01.02.01.02.01", description: "Nivelacion y perfilado en fondo de zanja", unit: "m2", metrado: 44.49, valuation: 116.12, progress: 100 },
    { code: "01.02.01.03.01", description: "Acarreo interno de material Dmax = 30 m", unit: "m3", metrado: 39.2, valuation: 438.26, progress: 100 },
    { code: "01.02.01.03.02", description: "Eliminacion de material excedente de excavaciones D = 5 km", unit: "m3", metrado: 39.2, valuation: 471.58, progress: 100 },
    { code: "01.02.02.01.01", description: "Concreto f'c=140 kg/cm2 + 30% PG para cimiento corrido", unit: "m3", metrado: 13, valuation: 6372.73, progress: 55.96 },
    { code: "01.02.02.01.02", description: "Encofrado y desencofrado normal para cimiento corrido", unit: "m2", metrado: 25.82, valuation: 1338.25, progress: 100 },
    { code: "01.02.02.04.01", description: "Concreto f'c=100 kg/cm2 + 30% PG para dado", unit: "m3", metrado: 3.46, valuation: 1359.12, progress: 100 },
    { code: "01.02.03.01.03", description: "Acero Fy=4200 kg/cm2 para pedestal", unit: "kg", metrado: 358.23, valuation: 2787.03, progress: 75.73 },
    { code: "01.02.03.02.03", description: "Acero Fy=4200 kg/cm2 para sobrecimiento armado", unit: "kg", metrado: 293.73, valuation: 2285.22, progress: 100 },
  ],
  detailedMetrados: [
    { code: "01.02.01.01.01", description: "Corte de plataforma", detail: "Aulas - ss.hh.; area 78.12, alto 0.60", quantity: 46.87, unit: "m3" },
    { code: "01.02.01.01.02", description: "Excavacion con maquinaria para cimiento corrido", detail: "Cimentacion; area 44.49, alto 0.60", quantity: 26.69, unit: "m3" },
    { code: "01.02.01.01.03", description: "Excavacion manual de zanja para dado", detail: "Ejes 1, 2 y 3; dados de 0.60 x 0.60 x 0.60", quantity: 3.46, unit: "m3" },
    { code: "01.02.02.01.01", description: "Concreto para cimiento corrido", detail: "Bloque aulas, ejes A, C, D, F y C-D/1-3", quantity: 13, unit: "m3" },
    { code: "01.02.02.01.02", description: "Encofrado y desencofrado de cimiento corrido", detail: "Bloque aulas, caras de ejes 1, 3, A, C, D, F y C-D/1-3", quantity: 25.82, unit: "m2" },
    { code: "01.02.03.01.03", description: "Acero para pedestal", detail: "Ver cuadro adjunto de metrado de acero", quantity: 358.23, unit: "kg" },
    { code: "01.02.03.02.03", description: "Acero para sobrecimiento armado", detail: "Ver cuadro adjunto de metrado de acero", quantity: 293.73, unit: "kg" },
  ],
  dailyHighlights: [
    "El metrado diario comprende registros del 01 al 30 de abril de 2026.",
    "Actividades repetitivas diarias: alquiler de almacen/oficina/guardiania, trazo y replanteo, EPP, proteccion colectiva, senalizacion y recursos de emergencia.",
    "Cerco provisional ejecutado por tramos de 20 m hasta completar 100 m.",
    "Cartel de obra ejecutado en dos avances de 0.50 und hasta completar 1.00 und.",
    "Excavaciones, acarreos, eliminacion de material, concreto y acero se registran por fechas y partidas en las planillas diarias.",
  ],
  staff: [
    { name: "Felix Yaranga Guillen", role: "Residente de obra", dni: "40581366", registry: "CIP 124398", participation: 1, months: 3, contract: "Contrato de trabajo de IOARR a plazo determinado N. 043-2026-MDUA/OGA" },
    { name: "Wilber Carbajal Sulca", role: "Supervisor de obra", dni: "70770363", registry: "CIP 281754", participation: 1, months: 3, contract: "Contrato de trabajo de IOARR a plazo determinado N. 040-2026-MDUA/OGA" },
    { name: "Almeyda Graceli Huamani Palomino", role: "Asistente tecnico", dni: "74435512", registry: "CIP 308836", participation: 1, months: 0.83, contract: "Orden de servicio N. 950" },
    { name: "Mayumi Rua Huanaco", role: "Asistente administrativo", dni: "48000411", registry: "Bachiller", participation: 1, months: 2.83, contract: "Orden de servicio N. 947" },
    { name: "Rhenan Diaz Meza", role: "Especialista de calidad", dni: "42516570", registry: "CIP 226257", participation: 1, months: 0.73, contract: "Orden de servicio N. 985" },
    { name: "Miquilson Casavilca Pillaca", role: "Especialista en seguridad", dni: "43802509", registry: "CIP 168091", participation: 1, months: 0.83, contract: "Orden de servicio N. 949" },
    { name: "Griss Edith Aquino Romero", role: "Almacenera", dni: "70238686", registry: "N/C", participation: 1, months: 2.83, contract: "Orden de servicio N. 948" },
    { name: "Especialista en hidraulica y sanitaria", role: "No corresponde / N/C", dni: "N/C", registry: "N/C", participation: 0, months: 0, contract: "N/C" },
    { name: "Especialista en mecanica electrica", role: "No corresponde / N/C", dni: "N/C", registry: "N/C", participation: 0, months: 0, contract: "N/C" },
    { name: "Maestro de obra", role: "No corresponde / N/C", dni: "N/C", registry: "N/C", participation: 0, months: 0, contract: "N/A" },
  ],
  controlQuestions: [
    { topic: "Riesgos atribuibles a la entidad", answer: "No existio riesgos que se atribuya como responsabilidad a la entidad." },
    { topic: "Riesgos atribuibles al ejecutor", answer: "Por el momento no se ha detectado algun tipo de riesgo que responsabilice a los ejecutores." },
    { topic: "Consultas por incompatibilidades o soluciones tecnicas", answer: "No hubo consultas; si hubo solicitudes de autorizacion para proceder con algunas actividades." },
    { topic: "Uso de recursos, equipos y personal", answer: "Se realizo verificacion durante el proceso de ejecucion." },
    { topic: "Controles de calidad", answer: "Se verifico la calidad y especificaciones tecnicas establecidas en el expediente tecnico de obra." },
    { topic: "Cumplimiento de planos", answer: "Los trabajos se ejecutaron en cumplimiento de especificaciones tecnicas y detalles de planos." },
    { topic: "Compatibilidad con cronograma", answer: "Las partidas valorizadas son coherentes con las partidas programadas antes del inicio del IOARR." },
    { topic: "Sustento de metrados", answer: "Cada partida valorizada cuenta con metrados diarios consolidados en un resumen." },
    { topic: "Reajustes por formula polinomica", answer: "No corresponde." },
    { topic: "Partidas con mayor metrado", answer: "Ninguna." },
  ],
  normativeControls: [
    { name: "Informe mensual de supervision y valorizacion", status: "Cumple", evidence: "Contenido del informe mensual y Anexo 01." },
    { name: "Valorizacion por metrados realmente ejecutados", status: "Cumple", evidence: "Planilla de metrados detallada, resumen de metrado mensual y planillas diarias." },
    { name: "Comparacion programado vs ejecutado", status: "Cumple", evidence: "Cronograma comparado y Curva S fisica/financiera." },
    { name: "Control fisico-financiero", status: "Observado", evidence: "Avance fisico 5.96% frente a programado 7.21%; avance financiero 9.87%." },
    { name: "Control de personal propuesto y presente", status: "Cumple", evidence: "Cuadro de personal propuesto/presente en obra para valorizacion N. 1." },
    { name: "Modificaciones al expediente tecnico", status: "Sin modificaciones", evidence: "Desagregado de modificaciones: ninguna; partidas nuevas: ninguna." },
    { name: "Presupuesto analitico y devengado", status: "Cumple", evidence: "Ejecucion de gasto actualizada al 30/04/2026 y presupuesto analitico modificado." },
    { name: "Panel fotografico", status: "Incluido en PDF fuente", evidence: "El documento completo queda embebido para consulta offline." },
  ],
  communications: [
    "Memorandum Multiple N. 20-2026-MDUA-GDTI/EOC-G, 01 de abril de 2026: creacion de usuario en INFOBRAS y baja del supervisor anterior.",
    "Memorandum Multiple N. 051-2026-MDUA/UFSLO-JOAE-J, 21 de abril de 2026: respuesta sobre saneamiento fisico legal de la I.E. 501390 Santoshari.",
    "Informe N. 013-2026-MDUA/UFSLO/WCS-SO: atencion a solicitud de aprobacion de cambio no significativo.",
    "Informe N. 018-2026-MDUA/UFSLO/WCS-SO: documento mediante el cual la supervision presenta el informe mensual.",
  ],
  findings: [
    "La obra se encuentra en leve retraso: avance fisico ejecutado 5.96% frente al programado acumulado 7.21%.",
    "El avance financiero acumulado es 9.87% respecto al PIM 2026.",
    "No se registran ampliaciones de plazo, paralizaciones, adicionales, mayores metrados ni partidas nuevas.",
    "Se reporta una discrepancia respecto al metrado diario del cuaderno de obra, por lo que la supervision valida metrados realmente ejecutados.",
    "Existe un requerimiento de modulo prefabricado pendiente en la Unidad Funcional de Logistica desde el 09 de abril de 2026, identificado como riesgo de retraso.",
  ],
  recommendations: [
    "Priorizar los tramites administrativos de requerimientos, especialmente el modulo prefabricado pendiente desde el 09 de abril de 2026.",
    "Concientizar a las dependencias administrativas sobre la Directiva 017-2023-CG para obras por administracion directa y sobre el plan de abastecimiento.",
    "Tramitar requerimientos dentro de los plazos de la directiva municipal y/o Ley 32069, Ley General de Contrataciones Publicas.",
    "Mantener control de metrados diarios, recursos, personal y calidad antes de formular la siguiente valorizacion.",
    "Sostener la comparacion mensual programado vs ejecutado y activar medidas correctivas si la brecha fisica aumenta.",
  ],
  conclusions: [
    "La supervision viene realizando labores conforme al expediente tecnico, directiva interna municipal y directiva de Contraloria aplicable.",
    "Durante abril de 2026 se aprobo la Valorizacion N. 01 con avance fisico mensual de 5.96% a nivel de costo directo.",
    "El avance fisico ejecutado se encuentra por debajo del programado acumulado de 7.21%, configurando leve retraso.",
    "La IOARR presenta avance financiero mensual y acumulado de 9.87% en funcion al PIM 2026.",
    "La valorizacion fue formulada con metrados realmente ejecutados y verificados por supervision.",
  ],
  sourceSections: [
    "Contenido del informe mensual de supervision mes de abril 2026",
    "Ficha tecnica",
    "Informacion del inspector o supervisor",
    "Ampliaciones de plazo y paralizaciones",
    "Memoria descriptiva",
    "Informe de conformidad",
    "Valorizacion mensual de obra",
    "Resumen de valorizacion de obra",
    "Cronograma comparado proyectado vs ejecutado",
    "Programacion para el siguiente mes",
    "Curva S",
    "Planilla de metrados detallado",
    "Resumen de metrado ejecutado en el mes",
    "Planilla de metrados por cada partida diarios",
    "Ejecucion fisica vs financiera",
    "Modificaciones al expediente tecnico de obra",
    "Modificaciones de presupuestos analiticos",
    "Panel fotografico",
  ],
};
